config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("account.urls")),
    path("social-auth/",
         include("social_django.urls", namespace="social")),
    path('images/', include('images.urls', namespace='images'))
]


if settings.DEBUG:

    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path

from images import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create,
         name='create'),
    path('detail/<int:image_id>/<slug:slug>/', views.image_detail,
         name='detail'),

    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
]

images/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils.text import slugify

User = get_user_model()


class Image(models.Model):

    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='images_created')
    user_likes = models.ManyToManyField(User,
                                        blank=True,
                                        related_name='images_liked')

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255,
                            blank=True)
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    total_likes = models.PositiveIntegerField(default=0)

    class Meta:
        indexes = [
            models.Index(fields=['-created']),
            models.Index(fields=['-total_likes'])
        ]
        ordering = ['-created']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', kwargs={
            "image_id": self.pk,
            "slug": self.slug
        })

    def __str__(self):
        return self.title

images/forms.py
import requests

from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify


from images.models import Image


class ImageCreateForm(forms.ModelForm):

    url = forms.URLField(widget=forms.HiddenInput)

    class Meta:
        model = Image
        fields = ('title', 'url', 'description')

    def clean_url(self):

        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg', 'png']
        extension = url.split('.')[-1]
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not '
                                        'match valid image extensions.')

        return url

    def save(self,
             force_insert=False,
             force_update=False,
             commit=True):

        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[-1].lower()
        image_name = f"{name}.{extension}"

        response = requests.get(image_url)
        image.image.save(image_name,
                         ContentFile(response.content),
                         save=False)

        if commit:
            image.save()
        return image

images/views.py
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from images.forms import ImageCreateForm
from images.models import Image

from actions.utils import create_action


@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')

    if image_id and action:
        try:
            image = Image.objects.get(pk=image_id)
            if action == 'like':
                image.user_likes.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.user_likes.remove(request.user)

            return JsonResponse({"status": "ok"})
        except Image.DoesNotExist:
            pass

    return JsonResponse({"status": "error"})


def image_detail(request, image_id, slug):
    # image = get_object_or_404(Image,
    #                           id=image_id,
    #                           slug=slug)

    image = (Image.objects
             .filter(id=image_id, slug=slug)
             .prefetch_related("user_likes")
             .first()
             )

    if not image:
        return HttpResponse(status=404)

    context = {
        'section': 'images',
        'image': image,
    }
    return render(request,
                  'images/image/detail.html',
                  context=context)


@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_image = form.save(commit=False)
            new_image.user = request.user
            new_image.save()
            create_action(request.user, 'bookmarked image', new_image)
            messages.success(request,
                             message="Image successfully created!")
            return redirect(new_image.get_absolute_url())

    else:
        form = ImageCreateForm(data=request.GET)

    context = {
        'section': 'images',
        'form': form,
    }

    return render(request,
                  template_name='images/image/create.html',
                  context=context)


@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 5)
    page = request.GET.get('page')
    images_only = request.GET.get('images_only')

    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if images_only:
            return HttpResponse('')

        images = paginator.page(paginator.num_pages)

    context = {'section': 'images',
               'images': images, }
    if images_only:
        return render(request,
                      'images/image/list_images.html',
                     context=context)

    return render(request,
                  'images/image/list.html',
                  context=context)

images/templates/images/image/create.html
{% extends "base.html" %}

{% block title %}
    Bookmark an image
{% endblock %}

{% block content %}
    <h1>Bookmark an image</h1>

    <img src="{{ request.GET.url }}" class="image-preview">

    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Bookmark it!">
    </form>

{% endblock %}

images/templates/images/image/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
    {{ image.title }}
{% endblock %}

{% block content %}
    <h1>{{ image.title }}</h1>

    <a href="{{ image.image.url }}">
        <img src="{% thumbnail image.image 300x0 %}" class="image-detail">
    </a>

    {% with total_likes=image.user_likes.count user_likes=image.user_likes.all %}

        <div class="image-info">
            <div>
                <span class="count">
                     <span class="total">{{ total_likes }}</span>
                    like{{ total_likes|pluralize }}
                </span>
                <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in user_likes %}un{% endif %}like"
                   class="like button">
                    {% if request.user not in user_likes %}
                        Like
                    {% else %}
                        Unlike
                    {% endif %}
                </a>
            </div>
            {{ image.description|linebreaks }}
        </div>

        <div class="image-likes">
            {% for user in image.user_likes.all %}
                <div>
                    {% if user.profile.photo %}
                        <img src="{{ user.profile.photo.url }}">
                    {% endif %}
                    <p>{{ user.first_name }}</p>
                </div>
            {% empty %}
                Nobody likes this image yet.
            {% endfor %}
        </div>
    {% endwith %}
{% endblock %}


{% block domready %}
    const url = '{% url "images:like" %}';

    var options = {
        method: 'POST',
        headers: {
            'X-CSRFToken': csrftoken
        },
        mode: 'same-origin'
    };

    const likeButton = document.querySelector('a.like');

    if (likeButton) {
        likeButton.addEventListener('click', function(e) {
            e.preventDefault();

            var formData = new FormData();
            formData.append('id', likeButton.dataset.id);
            formData.append('action', likeButton.dataset.action);

            options.body = formData;

            fetch(url, options)
                .then(response => response.json())
                .then(data => {
                    if (data.status === 'ok') {

                        var previousAction = likeButton.dataset.action;
                        var action = previousAction === 'like' ? 'unlike' : 'like';

                        likeButton.dataset.action = action;
                        likeButton.innerHTML = action;

                        var likeCount = document.querySelector('span.count .total');
                        var totalLikes = parseInt(likeCount.innerHTML);

                        likeCount.innerHTML =
                            previousAction === 'like'
                                ? totalLikes + 1
                                : totalLikes - 1;
                    }
                });
        });
    }
{% endblock domready %}

images/templates/images/image/list.html
{% extends "base.html" %}

{% block title %}Images bookmarked{% endblock %}
{% block content %}
    <h1>Images bookmarked</h1>
    <div id="image-list">
        {% include "images/image/list_images.html" %}
    </div>
{% endblock %}

{% block domready %}
    var page = 1;
    var emptyPage = false;
    var blockRequest = false;

    window.addEventListener('scroll', function(e) {

        var margin = document.body.clientHeight - window.innerHeight - 200;

        if (window.pageYOffset > margin && !emptyPage && !blockRequest) {

            blockRequest = true;
            page += 1;

            fetch('?images_only=1&page=' + page)
                .then(response => response.text())
                .then(html => {

                    if (html.trim() === '') {
                        emptyPage = true;
                    } else {
                        var imageList = document.getElementById('image-list');
                        imageList.insertAdjacentHTML('beforeEnd', html);
                        blockRequest = false;
                    }

                });
        }
    });

    // Запуск события прокрутки при загрузке
    window.dispatchEvent(new Event('scroll'));
{% endblock domready %}

images/templates/images/image/list_images.html
{% load thumbnail %}

{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image 300x300 crop="smart" as im %}
            <a href="{{ image.get_absolute_url }}">
                <img src="{{ im.url }}">
            </a>
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">
                {{ image.title }}
            </a>
        </div>
    </div>
{% endfor %}