config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("account.urls")),
    path("social-auth/",
         include("social_django.urls", namespace="social")),
    path('images/', include('images.urls', namespace='images'))
]


if settings.DEBUG:

    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path

from images import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create,
         name='create'),
    path('detail/<int:image_id>/<slug:slug>/', views.image_detail,
         name='detail'),

    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>

<div id="header">
    <span class="logo">Bookmarks</span>

    {% if user.is_authenticated %}
        <ul class="menu">
            <li {% if section == "dashboard" %}class="selected"{% endif %}>
                <a href="{% url 'dashboard' %}">My dashboard</a>
            </li>

            <li {% if section == "images" %}class="selected"{% endif %}>
                <a href="{% url 'images:list' %}">Images</a>
            </li>

            <li {% if section == "people" %}class="selected"{% endif %}>
                <a href="{% url 'user_list' %}">People</a>
            </li>
        </ul>
    {% endif %}
    <span class="user">
        {% if user.is_authenticated %}
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Log-out">
            </form>
        {% else %}
            <a href="{% url 'login' %}">Log-in</a>
        {% endif %}
    </span>

</div>

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">
                {{ message|safe }}

                <a href="#" class="close">x</a>
            </li>
        {% endfor %}
    </ul>
{% endif %}

<div id="content">
    {% block content %}
    {% endblock content %}
</div>


<script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
<script>
    const csrftoken = Cookies.get('csrftoken');
    document.addEventListener('DOMContentLoaded', (event) => {
// DOM загружена
        {% block domready %}
        {% endblock %}
    })
</script>


</body>
</html>